### ISSUE TITLE
Multiple filesroot

### ISSUE THREAD

**Issue by 1dot44mb** [blackcity/Backload#111]
Our web application has different functionalities.
Is it possible to use different "filesroot" property for different functionalities?
Eg.
- ProfilePictures will be uploaded to ~/profilepics
- Customer invoices will be uploaded to ~/invoices
  etc.

**Comment by Auersberg** [comment]
FilesRoot is meant to define the root storage location. For context based storage settings you should use objectContext or uploadContext which you can set client or server side.

Client side: 
Send it with the URL (all requests) or as body parameter (post requests).

Server side:
Use the configuration loaded even and set it in e.param.BackoadValues
<pre>
void Events_ConfigurationLoaded(IFileHandler sender, Contracts.Eventing.IConfigurationLoadedEventArgs e)
{
    if ([condition]) {
        // "images" will be concatenated to the storage path
        e.Param.BackloadValues.ObjectContext = "images";
    } else {
        e.Param.BackloadValues.ObjectContext = "music";
        // Create some subfolders
        if  ([condition]) {
            e.Param.BackloadValues.UploadContext = "soul";
        } else {
            e.Param.BackloadValues.UploadContext = "hiphop";
        }
    }
}
</pre>

**Comment by 1dot44mb** [comment]
Yes, what i meant is; multiple "root storage location"s.
ObjectContext and UploadContext are folders inside "filesroot" property.
In our scenario; multiple "filesroot" are needed to save different files coming from completely different modules of our web application into different storages.

**Comment by helgans** [comment]
You can change the "filesRoot" configuration attribute in code, e.g. within the "ConfigurationLoaded" event handler but this has an impact on all subsequent requests because the configuration is static for all requests. 

#### Method 1 (only avalable in latest release):
You can change the scope of the configuration to "request", so changes to the configuration only impacts the current request. But this is a Pro feature and only available in the latest release:
<pre>
// Sets the configuration to a request based scope. Default: "global"
&lt;backload webConfigContext="request" [...] /&gt;
</pre>

#### Method 2:
To change the root path without any impact you can use the "IncomingRequest" server side event. In this event the root path is ready, but file paths are not calculated yet (file paths are built using properties in BasicStorageInfo, see below):
<pre>
void Events_IncomingRequestStarted(IFileHandler sender, Contracts.Eventing.IIncomingRequestEventArgs e)
{
    string subDir = string.Empty;

    // storageType is a parameter you sent with the request (query or form)
    if (e.Param.CustomQueryValues.ContainsKey("storageType"))
        subDir = e.Param.CustomQueryValues["storageType"];
    else if (e.Param.CustomFormValues.ContainsKey("storageType"))
        subDir = e.Param.CustomFormValues["storageType"];

    if (!string.IsNullOrEmpty(subDir))
    {
        // e.Context.BasePath: Contains file server or application paths
        // sender.BasicStorageInfo: Used to create the file and thumbnail path
        sender.BasicStorageInfo.FileDirectory = e.Context.BasePath.LocalServer + "\\" + subDir + "\\";
        sender.BasicStorageInfo.FileDirectoryUrl = new Uri(e.Context.BasePath.WebAppRoot + "/" + subDir + "/");
        sender.BasicStorageInfo.ThumbsDirectory = sender.BasicStorageInfo.FileDirectory + "_thumbs\\";
        sender.BasicStorageInfo.ThumbsDirectoryUrl = new Uri(sender.BasicStorageInfo.FileDirectoryUrl, "_thumbs/");
    }
}
</pre>

**Comment by 1dot44mb** [comment]
2nd method is the way i went. Thanks.
