### ISSUE TITLE
Is it any kind of file uploader

### ISSUE THREAD

**Issue by tridipkolkata** [blackcity/Backload#65]
i heard the name plupload, fine uploader these are the library which people use to upload very large file from client side to server side. Backload is any similar kind of library?

please let me know. thanks

**Comment by Auersberg** [comment]
While PlUpload, Fine Uploader or jQuery File Upload are client side components, Backload is a server side component. It is called from these client side plugins. Backload runs as a library in a .NET environment on IIS within a .NET project.

**Comment by tridip-bba** [comment]
It can handle very large file suppose 5 Or 10 Gb?

**Comment by Auersberg** [comment]
In this case you can upload file chunks, where the client sends small parts of the file to the server side component (Backload). All client side Javascript plugins support this. When all chunks are uploaded, Backload merges these chunks to a single file whithout loading the whole file into memory. 

The [full demo package](https://github.com/blackcity/Backload/releases/download/v2.0.0.0/Backload.Standard.2.0.Full.zip) already has file chunking enabled in the examples (10Mb chunks). If you want to test these demos with 5Gb or 10Gb files you have to increase the chunk size, otherwise you'll get 500 or 1000 chunks. We recommend a maximum of 100-150 chunks per file, but this is very application specific.

https://github.com/blackcity/Backload/wiki/Chunked-files

Note: File chunking is a Pro feature but can be tested on your dev machine without restrictions.
