### ISSUE TITLE
Virtual path not properly mapped to file system

### ISSUE THREAD

**Issue by mjmcginty** [blackcity/Backload#74]
In the config file we have set filesRoot="~/filecabinet", which is a virtual directory.  When our StoreFileRequestStarted callback is called, e.Param.FileStatusItem.StorageInfo.FilePath is set to the web root path + filesRoot (with the tilde stripped) *not* the path to which the virtual directory is mapped.

   e.Context.Request.MapPath("/") + "/filecabinet"
is not the same as:
   e.Context.Request.MapPath("/filecabinet")

We are setting the correct path in the callback, and it does, in fact work, however, if that same physical folder does not exist in the web root (and the app pool context lacks permissions to create it) the upload fails, apparently it needs the file system to match its erroneously derived path before StoreFileRequestStarted is called.

We have worked around the issue by creating that directory in the web root (but that doesn't make this less of a flaw.)

System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormat(IFormatProvider provider, String format, Object[] args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
[snipped trace code]
[****]
   at Backload.Services.CoreServices.<>c__DisplayClasscc.<CreateSubFolders>b__cb()
[****]
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---

TIA,
Mark McGinty

**Comment by Auersberg** [comment]
Did you set `webFilesRoot `which is if fact the name of the virtual directory in IIS?
<pre>
     &lt;!-- webFilesRoot is the name of a virtual directory set in IIS Manager --&gt;
     &lt;backload webFilesRoot="filecabinet"   [...] &gt;
       &lt;!-- d:\Files\ is the physical path to the storage --&gt;
       &lt;fileSystem filesRoot="d:\Files\"  /&gt;
     &lt;/backload>
</pre>

We are aware that webFilesRoot is a bit misleading and changed it already in the coming 2.2 release.

George

**Comment by mjmcginty** [comment]
Thanks for the fast reply.

So filesRoot is a file system path?  And it treats non-FQ values as file-system relative to the web root, that makes sense now.

This web app runs on multiple virtual servers, the UNC path of the virtual directory is different for each, that exact file system location isn't known to the config files, so I set filesRoot="/" and <backload webFilesRoot="filecabinet" [...] /> as you suggested.

Our IT dept. is replacing our database server this weekend so I can't test it at the moment.  If you don't hear from me again you may assume our problem is corrected.  (I'll try to make it back with confirmation, though.)

Thanks again!
-MM

**Comment by Auersberg** [comment]
> So filesRoot is a file system path? And it treats non-FQ values as file-system relative to the web root

This is correct. The web app relative path `filesRoot="~/[path]/"` is there because IIS also maps this kind of paths to the web application root folder and internally we can make use of the `MapPath()` function. A developer does not have to set an absolute path which can be different between dev machine and production server.

In your external storage scenario you set `webFilesRoot` and `filesRoot` to the same values like you do in IIS Manager to add a virtual directory to an external storage location. This can also be an unc path. Note: In the current release `filesRoot` must end with a backslash (like in my example above) when using an FQ path.

2.2 changes:
In the coming 2.2 release we added a `virtualPathName `attribute to the `fileSystem` configuration element which does the same like `webFilesRoot`, but we leave `webFilesRoot` as a fallback for previous installations.

**Comment by mjmcginty** [comment]
I tested, it’s all good!  Thanks for your assistance.  Keep up the great work! J

 

 

Mark McGinty

Senior Software Engineer

CoStar Brokerage Applications
