### ISSUE TITLE
Exception: 

### ISSUE THREAD

**Issue by DaveDiest** [blackcity/Backload#84]
Hello,

I'm uploading a file of size 891.29 meg and after what looks like its all uploaded i get the following exception ** ' Exception occured while storing the file'.**  

I'm using your current demo for this with nothing changed.  For this try i had  chunk size set to 50000001 in demos.other.chunkingbasic.js    Smaller files work just fine such as a 200 meg file.

I get the following error: ' Exception occured while storing the file'

There are 18 part files in the uploads directory for this file.

I'm currently evaluating this software and i'm hoping that you can help.

attached screen shot of error
![image](https://cloud.githubusercontent.com/assets/6607536/14220185/16adf448-f824-11e5-9d62-065c26af7455.png)

**Comment by blackcity** [comment]
I've just tested it with a 1.2GB text file without any problems. For the test I used a quad core machine with 8GB ram.

Did you execute the test local or on a remote server, because file chunking is available in the Standard Edition only during development (see https://github.com/blackcity/Backload/wiki/editions). If you test it with IIS Express on your local machine it should work.

**Comment by DaveDiest** [comment]
I have a new machine now and it has 16 gigs memory and more CPU's.  Everything seems to work now.

Does your solution have logging so we can see more details on failures?

**Comment by blackcity** [comment]
You can setup tracing as in described in the tracing demo and set it up to tog to a file. You just need to uncomment the system.diagnostics section (web.config) of the demo, set your tracing level and enable tracing in web.backload.config file.

Additional info here:
https://github.com/blackcity/backload/wiki/Tracing#more-trace-output-listeners
