### ISSUE TITLE
Using Backload to GET files from custom location?

### ISSUE THREAD

**Issue by Abe-Froman** [blackcity/Backload#95]
After a file is uploaded to my server, I'm pushing it off to a remote fileshare and deleting it from ~/Uploads.

When I want to GET a file, is it possible to specify a location other than ~/Uploads to download it from?

Thanks in advance!

**Comment by Auersberg** [comment]
Depends on the kind of remote share. Can you give me more details about this and what you do exactly?

**Comment by Abe-Froman** [comment]
Sure. Basically in my controller I am processing form data and then if everything's valid:

    string uploadFolder = Server.MapPath("~/Uploads/" + Session["UniqueId"]);
    // AttachmentStorageRoot is some UNC (e.g. \\myserver\myfileshare)
    string destinationFolder = Path.Combine(ConfigurationManager.AppSettings["AttachmentStorageRoot"], model.Id);
                    
    List<string> attachments = new List<string>();

    if (Directory.Exists(uploadFolder) && new DirectoryInfo(uploadFolder).GetFiles().Count() > 0)
    {
        Directory.CreateDirectory(destinationFolder);
        foreach (FileInfo file in new DirectoryInfo(uploadFolder).GetFiles())
        {
            FileInfo copiedFile = file.CopyTo(Path.Combine(destinationFolder, file.Name));
            attachments.Add(copiedFile.FullName);
        }
    }

    // some further processing on the files' information

I figured I would need something like `handler.Events.GetFilesRequestStartedAsync += Events_GetFilesRequestStartedAsync;` in the `FileHandler()` action in BackloadController and then something like:

    private Task Events_GetFilesRequestStartedAsync(IFileHandler sender, IGetFilesRequestEventArgs e)
    {
        if (string.Compare(e.Context.HttpMethod, "GET", true) == 0)
        {
            e.Context.Configuration.FileSystem.FilesRoot = ConfigurationManager.AppSettings["AttachmentStorageRoot"];
            // What now?
        }
    }

I hope this is the info you're needing but let me know if there's something else.

**Comment by Auersberg** [comment]
Is it possible in your business logic to upload directly to the UNC share or do you really need to store the file in ~/Uploads temporarily?

**Comment by Abe-Froman** [comment]
Well the reason we're storing temporarily in uploads is because the model does not have an ID at the time the files are uploaded, so we don't know the full destination folder. The model only gets an ID after the form is submitted.

Technically, I could use a temporary folder on the UNC share and then clean it up after so I could make this work if it weren't possible to do what I'm trying to do. Just let me know if it's not possible, and I'll work around it.

**Comment by Auersberg** [comment]
It's not difficult to do what you want. 
Set SearchPath your GetFilesRequestStarted event handler.
<pre>
void Events_GetFilesRequestStartedAsync(IFileHandler sender, Backload.Contracts.Eventing.IGetFilesRequestEventArgs e)
{
    e.Param.SearchPath = @"\\FileServer\Files\";
}
</pre>
Now the Backload component searches in the unc share on GET requests. 

If you want to return a download URL to the client you first need to setup a virtual directory in IIS Manager to the UNC share (e.g. Files -> \\\\FileServer\Files\). The root download URL for this virtual directory (share folder) will now become something like this: "http:\\{yourserver}\Files\".
In a final step you'll need to adjust the download URLs, because they point to the configured directory (~/Uploads). Use the GetFilesRequestFinished event handler:
<pre>
void Events_GetFilesRequestFinished(IFileHandler sender, Backload.Contracts.Eventing.IGetFilesRequestEventArgs e)
{
    var status = e.Param.FileStatus;
    foreach (var file in status.Files)
    {
        file.FileUrl = @"http:\\{yourserver}\Files\" + file.FileName;
    }
}
</pre>

<br />
Maybe the way around is a little bit simplier: Configure the UNC share and virtual directory in Web.Backload.config and IIS Manager and only adjust the temporarily upload path. But this is up to you.

Note: In the next release we already added a new event which makes those things simplier.

**Comment by Abe-Froman** [comment]
Thanks, in this case I won't need to return a download URL, in fact we are purposely obfuscating to the users where the files are coming from.

Seems like `Events_GetFilesRequestStartedAsync` only works with a Task return type, void isn't allowed. Returning `null` from there results in a NullRefException.

**Comment by Auersberg** [comment]
> in fact we are purposely obfuscating to the users where the files are coming from.

So, setting e.Param.SearchPath to the path should be sufficient.

> Seems like  Events_GetFilesRequestStartedAsync  only works with a Task return type, void isn't allowed. Returning  null  from there results in a NullRefException.

In my example I used the synchronous event handler GetFilesRequestStarted, not the async GetFilesRequestStartedAsync . This is why I can use void as a return type.

> &lt;backload filesUrlPattern="\\myserver\share\{query:workitemid}\{name}&gt;

filesUrlPattern is usually be used to tell Backload how to format the download URL. It can be set to an absolute URL (e.g. http://[yourserver]/files) or to some placeholders (e.g. filename, query or form parameters, default: {link}). Backload populates these placeholders with the real values when it creates the URLs. In your case, you do not need this. Please do not set it to a UNC path, because internally a System.Uri instance is created and it may produce an exception if it is set to a UNC path. The ~/Backload/Config/_Defaults/Defauts.txt file covers all possible settings. Note: this setting can be only used in the Pro Edition: https://github.com/blackcity/Backload/wiki/Configuration#attributes

**Comment by Abe-Froman** [comment]
Ah, the Async event was what I didn't catch, thanks for pointing that out.

I got it working to suit my needs, pending a little further verification. Thanks so much!

    private void Events_GetFilesRequestStarted(IFileHandler sender, IGetFilesRequestEventArgs e)
    {
        e.Param.SearchPath = ConfigurationManager.AppSettings["AttachmentStorageRoot"];
        sender.Context.RequestType = RequestType.File;
        FileInfo requestedFile = new FileInfo(Path.Combine(e.Param.SearchPath, e.Param.CustomQueryValues["workItemId"], e.Param.BackloadValues.FileName));
        sender.Context.Response.AppendHeader("content-disposition", "attachment; filename=" + requestedFile.Name);
        sender.Context.Response.TransmitFile(requestedFile.FullName);
        sender.Context.Response.End();
    }
