### ISSUE TITLE
Using an event and want to add to result.

### ISSUE THREAD

**Issue by DaveDiest** [blackcity/Backload#96]
I'm currently using the StoreFileRequestFinishedAsync to call another service to process the file that was uploaded and lets call it Service X .   Service X passes back content that I want to pass back to the calling client.  How would you suggest I do this.  Is there a way to append data to the result?

 private  async Task Events_StoreFileRequestFinishedAsync(IFileHandler sender, Contracts.Eventing.IStoreFileRequestEventArgs e)

Thanks for you time.

**Comment by Auersberg** [comment]
There are several ways to achieve this.
If you're using the latest 2.2 release we added a `MetaData` property to the `IFileStatusItem` class. `MetaData` has a property called `PublicMetaData` of type object and is intended to return arbitrary custom data. 
If you use a previous version you can use IFileStatusItem.Message to return your custom data.

In this example we want to return some user data in a UserData object
<pre>
void Events_StoreFileRequestFinished(IFileHandler sender, Contracts.Eventing.IStoreFileRequestEventArgs e)
{
    var file = e.Param.FileStatusItem;
    var user = new UserData { firstName= "John", lastName = "Doe" };

    // Serialized as JSON and returned in result.files[0].extra.metaData (new in release 2.2)
    file.MetaData.PublicMetaData = user;

    // Serialized as (JSON) string and returned in result.files[0].message
    file.Message = Newtonsoft.Json.JsonConvert.SerializeObject(user);
}</pre>
If you use Fiddler you can see that your custom data is returned in `result.files[0].extra`.

**Comment by DaveDiest** [comment]
Thanks much,  that works and is easy.

Next question is i'm using Jquery upload.  If i want to 'fail' the upload so it shows up on the client as a fail is there a way to do that from within the 'Events_StoreFileRequestFinished()' ?

Thanks for the great help

-Dave

**Comment by Auersberg** [comment]
This depends on how you will handle the error: Return gracefully or throw an exception.

##### Gracefully:
This returns a Http status ok (200), but signals the client plugin that an error occured:
<pre>
void Events_StoreFileRequestFinished(IFileHandler sender, Contracts.Eventing.IStoreFileRequestEventArgs e)
{
    var file = e.Param.FileStatusItem;
    file.ErrorMessage = "Error gracefully handled";
    file.Success = false;
}
</pre>

<br />
##### Return Http exception status code:
Here an http status code >= 400 will be returned and you can add a message why this upload failed. Note: for security reasons it is usually not recommend to provide too much error details, especially no system error messages. But maybe you trust your users ;)
<pre>
// Add an HTTP exception catch block to your controller action
public async Task<ActionResult> FileHandler()
{
	try
	{
		// file handler code
	}
	// Http exception catch block
	catch (HttpException e)
	{
		return new HttpStatusCodeResult(e.GetHttpCode(), e.Message);
	}
	catch ()
	{
		return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
	}
}


void Events_StoreFileRequestFinished(IFileHandler sender, Contracts.Eventing.IStoreFileRequestEventArgs e)
{
    throw new HttpException((int)HttpStatusCode.BadRequest, "You produced an error!");
}
</pre>

<br />
#### Final note:
If an exception is returned to the client you my notice a JavaScript error (null reference exception). This is because of a bug in the download template (Basic Plus UI theme).  You can fix this in your view:
<pre>
// Search for this line in your download template:
&lt;span&gt;{%=file.extra.originalName%}&tl;/span&gt;

// and change it to:
&lt;span&gt;{%=file.name%}&tl;/span&gt;
</pre>
